name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build Executable (natter)
        run: pyinstaller --onefile natter.py --name natter_windows_x64.exe
      - name: Build Executable (natter-check)
        run: pyinstaller --onefile natter-check.py --name natter_check_windows_x64.exe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-executables
          path: |
            dist/natter_windows_x64.exe
            dist/natter_check_windows_x64-check.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build Executable (natter)
        run: pyinstaller --onefile natter.py --name natter_linux_x64
      - name: Build Executable (natter-check)
        run: pyinstaller --onefile natter-check.py --name natter_check_linux_x64
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-executables
          path: |
            dist/natter_linux_x64
            dist/natter_check_linux_x64

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: dist/
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: TODO New Release.
          draft: false
          prerelease: false
          files: dist/**